# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IP-QQWry
version:      v0.0.1
version_from: lib/IP/QQWry.pm
installdirs:  site
requires:
    Test::More:                    0.65
    version:                       0.651

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
